version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/samber/git-contrib-graph
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build ./...
      - run: go vet ./...
      - run: go get github.com/golang/lint/golint
      - run: golint ./...
      - run: docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      - run: docker build -t samber/git-contrib-graph .
      - run: docker push samber/git-contrib-graph
